# Generated by Django 4.1.7 on 2023-03-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_incrementablesingletonmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdGenerator',
        ),
    ]
